Repository 2025-Ureca-Snac/snac-client, pull requests merged in 2025-07, with the labels that each got.

#2 Build 자동머지 추가
  .github/CODEOWNERS
  .github/workflows/auto-merge.yml
Labels: BUILD

#3 feat tailwindCSS설치 후 세팅 및 라이브러리 설치
  app/globals.css
  app/page.tsx
  package-lock.json
  package.json
  postcss.config.mjs
  tailwind.config.js
Labels: BUILD

#4 [DRAFT] QI1-2-폴더-기초환경-세팅
  app/(shared)/components/Button.tsx
  app/(shared)/constants/index.ts
  app/(shared)/hooks/useLocalStorage.ts
  app/(shared)/types/index.ts
  app/(shared)/utils/index.ts
  app/blog/layout.tsx
  app/blog/page.tsx
  app/favicon.ico
  app/match/layout.tsx
  app/match/page.tsx
  app/page.tsx
  app/payment/layout.tsx
  app/payment/page.tsx
Labels: FEAT, STYLE

#14 DRAFT Qi1 33 공통 컴포넌트 데이터 카드 레이아웃 제작
  app/(shared)/components/DataItemCard.tsx
  app/(shared)/components/Header.tsx
  app/(shared)/components/HomePageClient.tsx
  app/api/cards/route.ts
  app/layout.tsx
  app/page.tsx
  public/KT.png
  public/KT.svg
  public/LGU+.svg
  public/LG_U+.png
  public/SKT.png
  public/SKT.svg
  tailwind.config.ts
Labels: FEAT, STYLE

#15 Qi1 3 로그인 레이아웃 제작 및 기능 구현
  app/(shared)/components/find-email-section.tsx
  app/(shared)/components/find-password-section.tsx
  app/(shared)/components/input-field.tsx
  app/(shared)/components/modal-portal.tsx
  app/(shared)/components/password-input.tsx
  app/(shared)/components/social-login-buttons.tsx
  app/(shared)/components/user-logo.tsx
  app/(shared)/components/user-profile.tsx
  app/(shared)/components/verification-input.tsx
  app/(shared)/hooks/useTimer.ts
  app/(shared)/stores/auth-store.ts
  app/(shared)/stores/index.ts
  app/(shared)/stores/modal-store.ts
  app/(shared)/stores/user-store.ts
  app/(shared)/types/auth-store.ts
  app/(shared)/types/find-section.ts
  app/(shared)/types/index.ts
  app/(shared)/types/modal-portal.ts
  app/(shared)/types/modal-store.ts
  app/(shared)/types/sign-up.ts
  app/(shared)/types/user-store.ts
  app/(shared)/utils/api.ts
  app/login/SearchModal.tsx
  app/login/layout.tsx
  app/login/page.tsx
  app/login/search-modal.tsx
  app/signUp/layout.tsx
  app/signUp/page.tsx
  package.json
Labels: FEAT, REFACTOR

#18 fix: package-lock 파일 동기화 되지 않아 npm ci 실패 에러 수정
  package-lock.json
Labels: FIX, BUILD

#17 feat: 틸 그린 색상 추가 (#38CB89)
  tailwind.config.ts
Labels: FEAT

#21 feat: 박스 그림자랑 카드 컴포넌트 배경(#F3F5F7) 추가
  tailwind.config.ts
Labels: STYLE

#22 Qi1 47 블로그 상세페이지 구현 및 빌드에러 수정 (Next 15 -> 14 로 다운그레이드)
  app/(shared)/components/BlogCard.tsx
  app/(shared)/types/modal-store.ts
  app/blog/admin/page.tsx
  app/blog/components/BlogContent.tsx
  app/blog/components/BlogDetailModal.tsx
  app/blog/components/BlogHero.tsx
  app/blog/components/MarkdownRenderer.tsx
  app/blog/data/blogPosts.ts
  app/blog/layout.tsx
  app/blog/page.tsx
  app/blog/utils/blogUtils.ts
  app/login/Login.tsx
  app/login/page.tsx
  app/page.tsx
  eslint.config.mjs
  package-lock.json
  package.json
  public/blog-bg-pattern.png
  public/blog2.png
  tsconfig.json
Labels: FIX, FEAT, BUILD

#23 Qi1 36 마이페이지 레이아웃 구현
  app/(shared)/components/Accordion.tsx
  app/(shared)/components/ActionButtons.tsx
  app/(shared)/components/AnimatedTabContent.tsx
  app/(shared)/components/ChangeNicknameModal.tsx
  app/(shared)/components/ChangePasswordModal.tsx
  app/(shared)/components/ChangePhoneModal.tsx
  app/(shared)/components/FavoriteListModal.tsx
  app/(shared)/components/PrivacyPolicyModal.tsx
  app/(shared)/components/ScoreCard.tsx
  app/(shared)/components/ServiceGuideModal.tsx
  app/(shared)/components/SettingList.tsx
  app/(shared)/components/SideMenu.tsx
  app/(shared)/components/SocialLoginModal.tsx
  app/(shared)/components/TabNavigation.tsx
  app/(shared)/components/modal-portal.tsx
  app/(shared)/components/social-login-buttons.tsx
  app/(shared)/stores/auth-store.ts
  app/(shared)/types/auth-store.ts
  app/(shared)/types/index.ts
  app/(shared)/types/user-store.ts
  app/api/cards/route.ts
  app/login/page.tsx
  app/login/search-modal.tsx
  app/myPage/layout.tsx
  app/myPage/page.tsx
  app/myPage/point/PointContent.tsx
  app/myPage/point/page.tsx
  app/myPage/purchase-history/page.tsx
  app/myPage/sales-history/page.tsx
  app/signUp/page.tsx
  package-lock.json
  public/google_login.svg
  public/google_mobile_login.svg
  public/information.png
Labels: FIX, FEAT

#29 Qi1 82 홈 레이아웃 제작
  app/(shared)/components/DataItemCard.tsx
  app/(shared)/components/Pagination.tsx
  app/(shared)/stores/home-store.ts
  app/(shared)/utils/generateQueryParams.ts
  app/api/cards/scroll/route.ts
  app/home/banner.tsx
  app/home/components/article-section.tsx
  app/home/components/filter.tsx
  app/home/components/modal.tsx
  app/home/components/sort.tsx
  app/home/data-avgs.tsx
  app/home/home-layout.tsx
  app/home/home-section.tsx
  app/page.tsx
  package-lock.json
  package.json
  public/arrow-right.svg
  public/banner.svg
  public/close.svg
  public/filter.svg
  public/refresh.svg
  public/telecom.svg
Labels: FIX, FEAT, STYLE, REFACTOR, CHORE

#32 QI1-91-거래-통계-API-연결
  app/home/data-avgs.tsx
  app/page.tsx
Labels: FIX, FEAT, REFACTOR

#31 QI1-87 가격-표시-토글-추가
  app/(shared)/components/DataItemCard.tsx
  app/(shared)/stores/home-store.ts
  app/(shared)/types/index.ts
  app/home/components/price-unit-toggle.tsx
  app/home/home-layout.tsx
  app/home/home-section.tsx
  public/KT.png
  public/LGU+.png
  public/SKT.png
  public/snac-price.svg
Labels: FIX, FEAT, REFACTOR

#42 QI1-107-마이페이지-api-연동
  app/(shared)/stores/auth-store.ts
  app/(shared)/stores/user-store.ts
  app/mypage/layout.tsx
  app/mypage/page.tsx
Labels: FEAT

#41 Qi1 106 로그인 api 연동
  app/(shared)/stores/auth-store.ts
  app/(shared)/types/auth-store.ts
  app/(shared)/utils/api.ts
  app/login/Login.tsx
  tsconfig.json
Labels: FIX, FEAT

#33 QI1-94-글-등록하기-레이아웃-수정-및-기능-구현
  app/(shared)/components/DataItemCard.tsx
  app/(shared)/stores/home-store.ts
  app/(shared)/utils/generateQueryParams.ts
  app/api/cards/scroll/route.ts
  app/home/components/filter.tsx
  app/home/components/modal.tsx
  app/home/components/sort.tsx
  app/home/home-layout.tsx
  app/home/home-section.tsx
  app/layout.tsx
  app/page.tsx
  package-lock.json
  package.json
  public/LG.png
  public/write.svg
Labels: FIX, FEAT, REFACTOR

#43 QI1-110-홈-관련-카드-수정
  app/(shared)/components/DataItemCard.tsx
  app/(shared)/types/card.ts
  app/home/home-layout.tsx
  app/home/home-section.tsx
  app/page.tsx
Labels: FIX, FEAT, CHORE

#45 QI1-112-홈-필터-단골-기능
  app/home/components/filter.tsx
Labels: CHORE

#47 Qi1 104 실시간 매칭 페이지 거래하기 소켓연동 구현
  app/(shared)/hooks/useGlobalWebSocket.ts
  app/(shared)/stores/match-store.ts
  app/(shared)/types/api-errors.ts
  app/match/MatchPage.tsx
  app/match/complete/CompletePage.tsx
  app/match/complete/components/EarningsDisplay.tsx
  app/match/complete/components/TransactionSummary.tsx
  app/match/components/MatchContent.tsx
  app/match/components/modal/TradeConfirmationModal.tsx
  app/match/hooks/useMatchingEvents.ts
  app/match/trading/TradingPage.tsx
  app/match/trading/components/ConfirmationStep.tsx
  app/match/trading/components/PaymentStep.tsx
  app/match/trading/components/UploadDataStep.tsx
  app/match/trading/components/VerificationStep.tsx
  app/match/trading/hooks/useTradingWebSocket.ts
Labels: FEAT

#49 Qi1 106 로그인 api 연동
  app/(shared)/components/TabNavigation.tsx
  app/(shared)/components/find-email-section.tsx
  app/(shared)/components/find-password-section.tsx
  app/(shared)/components/input-field.tsx
  app/(shared)/components/input-with-button.tsx
  app/(shared)/components/modal-portal.tsx
  app/(shared)/components/password-input.tsx
  app/(shared)/components/social-login-buttons.tsx
  app/(shared)/components/verification-input.tsx
  app/(shared)/types/find-section.ts
  app/(shared)/types/formComponents.ts
  app/(shared)/types/history-card.ts
  app/(shared)/types/modal-store.ts
  app/(shared)/types/sms-types.ts
  app/(shared)/utils/browser-detection.ts
  app/(shared)/utils/password-validation.ts
  app/(shared)/utils/phone-utils.ts
  app/(shared)/utils/sms-format.ts
  app/(shared)/utils/sms-support.ts
  app/login/Login.tsx
  app/login/search-modal.tsx
  app/signUp/page.tsx
Labels: FIX, FEAT, STYLE, REFACTOR

#48 Qi1 118 홈페이지 및 헤더 UI 완성도 수정
  app/(shared)/components/Accordion.tsx
  app/(shared)/components/DataItemCard.tsx
  app/(shared)/components/Header.tsx
  app/(shared)/components/MenuLink.tsx
  app/(shared)/components/TabNavigation.tsx
  app/globals.css
  app/home/banner.tsx
  app/home/home-layout.tsx
  app/mypage/page.tsx
  app/page.tsx
Labels: STYLE

#53 Qi1 128 관리자 페이지 레이아웃 만들기
  .npmrc
  app/(shared)/stores/use-admin-store.ts
  app/(shared)/stores/use-blog-store.ts
  app/admin/blog/blog-filter.tsx
  app/admin/blog/blog-table.tsx
  app/admin/blog/delete-confirm-modal.tsx
  app/admin/blog/page.tsx
  app/admin/components/dashboard.tsx
  app/admin/components/report-types-chart.tsx
  app/admin/components/weekly-reports-chart.tsx
  app/admin/layout.tsx
  app/admin/page.tsx
  app/blog/admin/ToastEditor.tsx
  app/blog/admin/page.tsx
  next.config.ts
  package-lock.json
  package.json
  public/database.svg
  public/edit.svg
  public/issue.svg
  public/manager.svg
  public/menu.svg
  public/newReport.svg
  public/plus.svg
  public/post.svg
  public/report.svg
  public/totalUser.svg
  public/trash.svg
  tailwind.config.ts
Labels: FEAT, CHORE

#51 Qi1 122 구매글 판매글 거래하기 연동
  app/(shared)/components/DataItemCard.tsx
  app/(shared)/components/FilterButtons.tsx
  app/(shared)/components/FilterGroup.tsx
  app/(shared)/components/FilterOption.tsx
  app/(shared)/components/TradeConfirmationModal.tsx
  app/(shared)/components/payment-summary.tsx
  app/(shared)/components/product-details.tsx
  app/(shared)/components/progress-steps.tsx
  app/(shared)/stores/home-store.ts
  app/(shared)/types/card.ts
  app/(shared)/utils/carrier-utils.ts
  app/(shared)/utils/generateQueryParams.ts
  app/home/components/filter.tsx
  app/home/components/modal.tsx
  app/home/home-layout.tsx
  app/home/home-section.tsx
  app/page.tsx
  app/payment/complete/page.tsx
  app/payment/page.tsx
Labels: FIX, FEAT, REFACTOR

#56 Qi1 133 실시간 매칭 페이지 필터 변경 및 취소 처리
  app/(shared)/hooks/useGlobalWebSocket.ts
  app/(shared)/hooks/useWebSocketGuard.ts
  app/(shared)/stores/websocket-store.ts
  app/match/components/modal/TradeConfirmationModal.tsx
  app/match/components/seller/DataAmountInput.tsx
  app/match/components/user/UserCard.tsx
  app/mypage/page.tsx
  app/page.tsx
Labels: FEAT, CHORE

#58 Qi1 115 admin 페이지 - 블로그
  app/(shared)/stores/use-admin-store.ts
  app/(shared)/stores/use-blog-store.ts
  app/admin/blog/blog-table.tsx
  app/admin/blog/page.tsx
  app/admin/components/dashboard.tsx
  app/admin/layout.tsx
  app/blog/admin/page.tsx
  app/blog/page.tsx
  next.config.ts
Labels: FEAT, CHORE

#60 fix: 로그인 안되는 현상 수정
  app/(shared)/stores/auth-store.ts
  app/(shared)/types/auth-store.ts
Labels: FIX

#64 QI1-107-마이페이지-api-연동
  app/(shared)/stores/auth-store.ts
Labels: FIX
