Repository 2025-Ureca-Snac/snac-client, pull requests merged in 2025-08, with the labels that each got.

#68 Qi1 107 마이페이지 api 연동
  app/(shared)/components/SocialLoginModal.tsx
  app/(shared)/components/settlement-modal.tsx
  app/(shared)/stores/auth-store.ts
  app/(shared)/stores/user-store.ts
  app/(shared)/types/user-store.ts
  app/certification/page.tsx
  app/mypage/point/page.tsx
Labels: FIX, FEAT

#69 Qi1 115 블로그 admin 페이지
  app/(shared)/components/BlogCard.tsx
  app/(shared)/stores/use-blog-store.ts
  app/admin/blog/blog-detail-modal.tsx
  app/admin/blog/blog-table.tsx
  app/admin/blog/delete-confirm-modal.tsx
  app/blog/BlogPageClient.tsx
  app/blog/[id]/BlogPostPageClient.tsx
  app/blog/[id]/blog-post-page-client.tsx
  app/blog/[id]/page.tsx
  app/blog/admin/page.tsx
  app/blog/components/BlogContent.tsx
  app/blog/components/BlogDetailModal.tsx
  app/blog/components/BlogDetailPage.tsx
  app/blog/data/blogPosts.ts
  app/blog/page.tsx
  app/home/components/article-section.tsx
Labels: FEAT

#73 Qi1 155 관리자 헤더 링크
  app/(shared)/components/Header.tsx
  app/(shared)/components/MenuLink.tsx
  public/admin.svg
  public/login.svg
  public/logo_mobile.svg
  public/matching.svg
  public/user.svg
Labels: FEAT

#74 Qi1 156 페이지네이션 커서 연동 수정
  app/(shared)/components/Pagination.tsx
  app/page.tsx
Labels: FIX, STYLE

#75 Qi1 149 구매글 판매글 취소 status 처리하기
  app/(shared)/components/DataItemCard.tsx
  app/(shared)/components/HistoryDetailModal.tsx
  app/(shared)/components/progress-steps-detail.tsx
  app/(shared)/components/trading-history-page.tsx
  app/(shared)/constants/cancel-reasons.ts
  app/(shared)/types/history-card.ts
  app/home/components/modal.tsx
  app/home/home-section.tsx
Labels: FEAT, STYLE

#78 QI1-158-헤더-다크모드-라이트-모드
  app/(shared)/components/Header.tsx
  app/(shared)/components/MenuLink.tsx
  app/(shared)/components/ThemSwitch.tsx
  package-lock.json
  package.json
  public/dark.svg
  public/light.svg
  public/lightDarkMode.svg
  public/matching.svg
Labels: FEAT, STYLE

#82 Qi1 107 마이페이지 api 연동
  app/(shared)/components/DataItemCard.tsx
  app/(shared)/components/SocialLoginModal.tsx
  app/(shared)/components/cancel-modal.tsx
  app/(shared)/components/inquiry-modal.tsx
  app/(shared)/components/recharge-modal.tsx
  app/(shared)/components/refund-modal.tsx
  app/(shared)/components/settlement-modal.tsx
  app/(shared)/components/social-login-buttons.tsx
  app/(shared)/components/transfer-modal.tsx
  app/(shared)/stores/auth-store.ts
  app/(shared)/types/cancel-modal.ts
  app/(shared)/types/point-content.ts
  app/(shared)/types/recharge-modal.ts
  app/certification/page.tsx
  app/mypage/point/PointContent.tsx
  app/mypage/point/page.tsx
  app/payment/fail/page.tsx
  app/payment/page.tsx
  app/payment/process/page.tsx
  app/payment/success/page.tsx
  package-lock.json
  package.json
Labels: FIX

#81 Qi1 148 단골 등록 홈페이지 필터링 거래 후 등록
  app/(shared)/components/DataItemCard.tsx
  app/(shared)/components/HistoryDetailModal.tsx
  app/(shared)/components/TradingHistoryCard.tsx
  app/(shared)/components/trading-history-page.tsx
  app/(shared)/stores/home-store.ts
  app/(shared)/types/card.ts
  app/(shared)/types/history-card.ts
  app/home/components/filter.tsx
  app/page.tsx
Labels: FEAT, STYLE

#83 QI1-174 헤더 제거
  app/match/MatchPage.tsx
Labels: FIX

#88 Qi1 175 실시간 매칭 0803 개선
  app/(shared)/hooks/useGlobalWebSocket.ts
  app/(shared)/stores/match-store.ts
  app/(shared)/stores/websocket-store.ts
  app/match/MatchPage.tsx
  app/match/complete/CompletePage.tsx
  app/match/complete/components/TransactionSummary.tsx
  app/match/components/CategoryFilter.tsx
  app/match/components/FilterSection.tsx
  app/match/components/ResultSection.tsx
  app/match/components/TestPanel.tsx
  app/match/components/modal/TradeConfirmationModal.tsx
  app/match/trading/TradingPage.tsx
  app/match/trading/components/ConfirmationStep.tsx
  app/match/trading/components/ShowPhoneStep.tsx
  app/match/trading/components/UploadDataStep.tsx
  app/match/trading/components/WaitingPaymentStep.tsx
  app/match/types/match.ts
Labels: FIX

#89 Qi1 169 관리자 오류 수정
  app/(shared)/stores/use-dispute-store.ts
  app/admin/dispute/components/dispute-detail-modal.tsx
  app/admin/dispute/components/resolve-modal.tsx
  app/admin/dispute/qna/page.tsx
  app/admin/dispute/report/page.tsx
Labels: FEAT, STYLE

#90 Qi1 186 단골 필터링 안되는 현상
  app/(shared)/utils/generateQueryParams.ts
  app/home/banner.tsx
  app/page.tsx
Labels: FIX

#91 fix: SEO 개선 전체
  app/layout.tsx
Labels: FIX

#98 Qi1 192 실시간 매칭 페이지 쓸모없는 안내멘트 제거
  app/match/MatchPage.tsx
  app/match/complete/CompletePage.tsx
  app/match/complete/components/ActionButtons.tsx
  app/match/complete/components/EarningsDisplay.tsx
  app/match/components/IncomingRequestsPanel.tsx
  app/match/trading/TradingPage.tsx
  app/match/trading/components/ConfirmationStep.tsx
  app/match/trading/components/TradingSteps.tsx
  app/match/trading/components/TransferStep.tsx
Labels: FIX, FEAT

#101 QI1-202-평균-단가-여백-수정
  app/home/data-avgs.tsx
Labels: STYLE

#106 chore: 구글 크롤링봇 선언
  public/robots.txt
Labels: CHORE

#102 feat: CreateButton 컴포넌트 추가 및 홈 페이지에 통합
  app/(shared)/components/CreateButton.tsx
  app/page.tsx
Labels: FIX, STYLE

#103 Qi1 107 마이페이지 api 연동
  app/(shared)/components/AnimatedTabContent.tsx
  app/(shared)/components/ChangePasswordModal.tsx
  app/(shared)/components/ChangePhoneModal.tsx
  app/(shared)/components/PrivacyPolicyModal.tsx
  app/(shared)/components/ScoreCard.tsx
  app/(shared)/components/ServiceGuideModal.tsx
  app/(shared)/components/TabNavigation.tsx
  app/(shared)/components/ThemeModal.tsx
  app/(shared)/components/mypage-bottom-buttons.tsx
  app/(shared)/components/trading-history-page.tsx
  app/(shared)/constants/settings-data.ts
  app/(shared)/constants/side-menu-data.ts
  app/(shared)/stores/auth-store.ts
  app/(shared)/types/animated-tab-content.ts
  app/(shared)/types/point-content.ts
  app/(shared)/utils/setting-handlers.ts
  app/mypage/components/mypage-content.tsx
  app/mypage/layout.tsx
  app/mypage/mypage-page-client.tsx
  app/mypage/point/PointContent.tsx
  app/mypage/point/page.tsx
  app/mypage/report-history/page.tsx
  app/mypage/settings/layout.tsx
  app/mypage/settings/page.tsx
  app/mypage/settings/settings-page-client.tsx
Labels: FIX, REFACTOR

#104 Qi1 126 블로그 seo 개선
  app/(shared)/components/ChangePhoneModal.tsx
  app/(shared)/components/ConfirmationModal.tsx
  app/(shared)/components/DataItemCard.tsx
  app/(shared)/components/HistoryDetailModal.tsx
  app/(shared)/components/ScoreCard.tsx
  app/(shared)/components/TabNavigation.tsx
  app/(shared)/components/TradingHistoryCard.tsx
  app/(shared)/components/product-details.tsx
  app/(shared)/components/trading-history-page.tsx
  app/(shared)/hooks/useSwipeNavigation.ts
  app/(shared)/stores/balance-store.ts
  app/(shared)/types/index.ts
  app/(shared)/types/point-content.ts
  app/admin/layout.tsx
  app/blog/[id]/page.tsx
  app/cards/cards-layout.tsx
  app/cards/cards-section.tsx
  app/cards/data-avgs.tsx
  app/cards/page.tsx
  app/home/home-section.tsx
  app/mypage/point/PointContent.tsx
  app/mypage/point/page.tsx
  app/mypage/report-history/page.tsx
  app/trade/[cardId]/components/action-buttons.tsx
  app/trade/[cardId]/components/card-info.tsx
  app/trade/[cardId]/components/structured-data.tsx
  app/trade/[cardId]/layout.tsx
  app/trade/[cardId]/page.tsx
  app/trade/[cardId]/trade-content.tsx
  app/trade/[cardId]/trade-page-client.tsx
Labels: FEAT, REFACTOR

#107 QI1-207-Footer-수정
  app/(shared)/components/DesktopFooter.tsx
  app/(shared)/components/MobileFooter.tsx
Labels: CHORE

#109 style: 판매 비활성화 버튼 좀더 잘보이게 디자인
  app/match/components/seller/SellerStatusToggle.tsx
Labels: STYLE

#117 QI1-214-실시간-페이지-햄버거-누를때-다크모드-설정
  app/(shared)/components/Header.tsx
Labels: FIX

#118 style: 데이터 카드 반응형 수정
  app/(shared)/components/DataItemCard.tsx
Labels: STYLE

#116 Qi1 211 관리자 새로고침
  app/(shared)/components/Header.tsx
  app/(shared)/components/user-logo.tsx
  app/(shared)/stores/use-admin-store.ts
  app/(shared)/stores/use-dispute-store.ts
  app/admin/dispute/components/dispute-detail-modal.tsx
  app/admin/dispute/lib/constants.tsx
  app/admin/dispute/qna/page.tsx
  app/admin/dispute/report/page.tsx
Labels: FEAT, STYLE

#119 chore: 파비콘 변경
  app/favicon.ico
Labels: CHORE

#123 feat: 블로그 배너
  app/(shared)/components/blog-intro-banner.tsx
  app/HomePage.tsx
  public/blog1-non.png
Labels: FEAT

#131 Qi1 222 온보딩 배너 UI 수정
  app/home/components/introduction.tsx
Labels: STYLE, CHORE

#133 Qi1 221 프론트 최종본
  app/(shared)/components/AnimatedTabContent.tsx
  app/(shared)/components/DataUploadSection.tsx
  app/(shared)/components/Header.tsx
  app/(shared)/components/HistoryDetailModal.tsx
  app/(shared)/components/trading-history-page.tsx
  app/mypage/point/PointContent.tsx
  app/mypage/point/page.tsx
  app/mypage/report-history/page.tsx
  public/log-out.svg
Labels: FIX

#132 Qi2 001 전체 홈페이지 완성도 블로그 실시간 수정
  app/blog/[id]/blog-post-content.tsx
  app/match/trading/TradingPage.tsx
Labels: CHORE

#135 feat: 스크롤 인디케이터 추가
  app/home/components/introduction.tsx
Labels: FEAT
